### PR TITLE
Allow skip http wait

### PR DESCRIPTION
**Pull request by benjefferies**
Allow skip of the http wait plugin by adding -Dhttp.wait.skip to the
maven command or <skip>true</skip> to the configuration

### CODE REVIEW

**Comment by benjefferies** [comment]
Hi @tsundberg. I'm using the plugin and it works a treat. The problem I have is if I want to skip the phase in the maven build which doesn't bring up a service that the plugin depends on the build fails. In this scenario it would be good to skip it somehow i.e. `mvn install -Dhttp.wait.skip`

**Comment by tsundberg** [comment]
Thank you!

Glad to hear that it helps you.

/Thomas

**Comment by benjefferies** [comment]
Awesome @tsundberg is it possible to push a release artifact to maven? Not sure if I'd have access to do it?

**Comment by tsundberg** [comment]
You don't have access to push to Maven central. I am trying to remember how to do it now. I also updated the the documentation. Should be available on Maven central in a couple of hours.

**Pull request merged**
